language: python

python:
  - '2.6'
  - '2.7'

before_install:
  - sudo apt-get update && sudo apt-get install python-setuptools python-nose python-coverage python-django

install: ./build.sh
script: ./test.sh
