language: python

python:
  - '2.6'
  - '2.7'

env:
  - DJANGO_VERSION=1.3.1

before_install:
  - pip install coverage Django==$DJANGO_VERSION
  - pip install --upgrade nose

install: ./build.sh
script: ./test.sh
